name: a2ktik_kar
description: "A2ktik Karaoke helpers"
version: 0.1.1
homepage:
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  a2ktik_asset:
    git:
      url: https://github.com/a2ktik/a2ktikcommonpublic
      path: packages/a2ktik_asset
      ref: dart3a
  flutter:
    sdk: flutter
  playlr_audio_player_blue_fire:
    git:
      url: https://github.com/tekaly/playlr.git
      path: packages_flutter/playlr_audio_player_blue_fire
      ref: dart3a
    version: '>=0.0.1'
  festenao_lyrics_player:
    git:
      url: https://github.com/tekaly/festenao
      ref: dart3a
      path: packages_flutter/festenao_lyrics_player
    version: '>=0.1.1'
  festenao_media_base_app:
    git:
      url: https://github.com/tekaly/festenao
      ref: dart3a
      path: packages_flutter/festenao_media_base_app
  festenao_common_flutter:
    git:
      url: https://github.com/tekaly/festenao
      ref: dart3a
      path: packages_flutter/festenao_common_flutter
  playlr_audio_player:
    git:
      url: https://github.com/tekaly/playlr.git
      ref: dart3a
      path: packages_flutter/playlr_audio_player
  tekartik_file_cache_flutter:
    git:
      url: https://github.com/tekaly/playlr.git
      ref: dart3a
      path: packages_flutter/file_cache_flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=5.0.0"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
